using Microsoft.EntityFrameworkCore;
using Sompriti.Erp.Application.Common;
using Sompriti.Erp.Domain.Common;
using Sompriti.Erp.Domain.Entities;
using Sompriti.Erp.Domain.Enums;
using Sompriti.Erp.Domain.Rules;

namespace Sompriti.Erp.Application.MasterData;

/// <summary>Customer or supplier. Mobile number is returned in display form (01XXXXXXXXX).</summary>
public sealed record PartyDto(
    Guid Uuid, string Name, string Code, string MobileNumber, string? Nid, string? Tin, string? Address,
    string? City, string? State, string? PostalCode, Guid Revision, DateTimeOffset CreatedDate,
    DateTimeOffset UpdatedDate, string CreatedByUserName, string UpdatedByUserName);

public sealed record PartySaveRequest(
    string? Name, string? MobileNumber, string? Nid, string? Tin, string? Address, string? City,
    string? State, string? PostalCode, Guid? Revision);

/// <summary>Shared logic for customers and suppliers.</summary>
public abstract class PartyService<TParty>(IAppDbContext db) where TParty : PartyEntity, new()
{
    protected readonly IAppDbContext Db = db;
    protected abstract string Label { get; }
    protected DbSet<TParty> Set => Db.Set<TParty>();

    /// <summary>True when the party is used by at least one active DRAFT order.</summary>
    protected abstract Task<bool> UsedByDraftAsync(Guid id, CancellationToken ct);
    /// <summary>True when an active user is linked to this party.</summary>
    protected abstract Task<bool> LinkedToUserAsync(Guid id, CancellationToken ct);

    private static readonly Dictionary<string, System.Linq.Expressions.Expression<Func<TParty, object?>>> SortMap = new()
    {
        ["name"] = x => x.Name,
        ["code"] = x => x.Code,
        ["city"] = x => x.City,
        ["createdDate"] = x => x.CreatedDate,
    };

    public static PartyDto ToDto(PartyEntity p) => new(p.Uuid, p.Name, p.Code ?? "", BdMobile.ToDisplay(p.MobileNumber), p.Nid, p.Tin,
        p.Address, p.City, p.State, p.PostalCode, p.Revision, p.CreatedDate, p.UpdatedDate, p.CreatedByUserName, p.UpdatedByUserName);

    public async Task<PagedResult<PartyDto>> ListAsync(PageQuery q, CancellationToken ct)
    {
        var query = Set.AsNoTracking().Where(x => x.Status == RecordStatus.Active);
        if (q.Term is { } t)
        {
            var term = t.ToLower();
            var mobile = BdMobile.Normalize(t);
            query = query.Where(x => x.Name.ToLower().Contains(term) || x.Code!.Contains(term)
                                     || (mobile != null && x.MobileNumber == mobile));
        }
        var page = await query.ApplySort(q.Sort, SortMap, s => s.OrderByDescending(x => x.CreatedDate))
            .ToPagedAsync(q, p => p, ct);
        return new PagedResult<PartyDto>(page.Items.Select(ToDto).ToList(), page.Page, page.PageSize, page.TotalCount);
    }

    public async Task<IReadOnlyList<DropdownItem>> DropdownAsync(string? search, CancellationToken ct)
    {
        var query = Set.AsNoTracking().Where(x => x.Status == RecordStatus.Active);
        if (!string.IsNullOrWhiteSpace(search))
        {
            var term = search.Trim().ToLower();
            query = query.Where(x => x.Name.ToLower().Contains(term) || x.Code!.Contains(term));
        }
        return await query.OrderBy(x => x.Name).Take(50)
            .Select(x => new DropdownItem(x.Uuid, x.Code!, x.Name, x.Name + " (" + x.Code + ")"))
            .ToListAsync(ct);
    }

    public async Task<PartyDto> GetAsync(Guid id, CancellationToken ct)
    {
        var p = await Set.AsNoTracking().FirstOrDefaultAsync(x => x.Uuid == id && x.Status == RecordStatus.Active, ct);
        return ToDto(p.OrNotFound(Label));
    }

    public async Task<PartyDto> CreateAsync(PartySaveRequest r, CancellationToken ct)
    {
        var mobile = Validate(r);
        var p = new TParty { Uuid = Guid.NewGuid() };
        Apply(p, r, mobile);
        Set.Add(p);
        await Db.SaveChangesAsync(ct); // code is generated by the database sequence
        return ToDto(p);
    }

    public async Task<PartyDto> UpdateAsync(Guid id, PartySaveRequest r, CancellationToken ct)
    {
        var mobile = Validate(r);
        var p = (await Set.FirstOrDefaultAsync(x => x.Uuid == id && x.Status == RecordStatus.Active, ct)).OrNotFound(Label);
        RevisionGuard.Check(Db, p, r.Revision ?? Guid.Empty);
        Apply(p, r, mobile);
        await Db.SaveChangesAsync(ct);
        return ToDto(p);
    }

    public async Task DeleteAsync(Guid id, Guid revision, CancellationToken ct)
    {
        var p = (await Set.FirstOrDefaultAsync(x => x.Uuid == id && x.Status == RecordStatus.Active, ct)).OrNotFound(Label);
        RevisionGuard.Check(Db, p, revision);
        if (await UsedByDraftAsync(id, ct))
            throw DomainException.Rule(ErrorCodes.InUseByDraft, $"This {Label.ToLower()} is used by draft orders. Finalize, void or delete those drafts first.");
        if (await LinkedToUserAsync(id, ct))
            throw DomainException.Rule(ErrorCodes.BusinessRule, $"This {Label.ToLower()} is linked to a user account. Remove the link first.");
        p.Status = RecordStatus.Deleted;
        await Db.SaveChangesAsync(ct);
    }

    private string Validate(PartySaveRequest r)
    {
        var v = new Validator()
            .Required("name", r.Name, $"{Label} name", 150)
            .Required("mobileNumber", r.MobileNumber, "Mobile number")
            .MaxLength("nid", r.Nid, "NID", 30)
            .MaxLength("tin", r.Tin, "TIN", 30)
            .MaxLength("address", r.Address, "Address", 300)
            .MaxLength("city", r.City, "City", 100)
            .MaxLength("state", r.State, "State", 100)
            .MaxLength("postalCode", r.PostalCode, "Postal code", 20);
        var mobile = BdMobile.Normalize(r.MobileNumber);
        v.When(!string.IsNullOrWhiteSpace(r.MobileNumber) && mobile is null, "mobileNumber",
            "Enter a valid Bangladesh mobile number, e.g. 01712345678.");
        v.ThrowIfInvalid();
        return mobile!;
    }

    private static void Apply(TParty p, PartySaveRequest r, string mobile)
    {
        p.Name = r.Name!.Trim();
        p.MobileNumber = mobile;
        p.Nid = Validator.Clean(r.Nid);
        p.Tin = Validator.Clean(r.Tin);
        p.Address = Validator.Clean(r.Address);
        p.City = Validator.Clean(r.City);
        p.State = Validator.Clean(r.State);
        p.PostalCode = Validator.Clean(r.PostalCode);
    }
}

public sealed class CustomerService(IAppDbContext db) : PartyService<Customer>(db)
{
    protected override string Label => "Customer";

    protected override Task<bool> UsedByDraftAsync(Guid id, CancellationToken ct) =>
        Db.SalesOrders.AnyAsync(o => o.PartyUuid == id && o.Status == RecordStatus.Active && o.PostingStatus == PostingStatus.Draft, ct);

    protected override Task<bool> LinkedToUserAsync(Guid id, CancellationToken ct) =>
        Db.Users.AnyAsync(u => u.CustomerUuid == id && u.Status == RecordStatus.Active, ct);
}

public sealed class SupplierService(IAppDbContext db) : PartyService<Supplier>(db)
{
    protected override string Label => "Supplier";

    protected override Task<bool> UsedByDraftAsync(Guid id, CancellationToken ct) =>
        Db.PurchaseOrders.AnyAsync(o => o.PartyUuid == id && o.Status == RecordStatus.Active && o.PostingStatus == PostingStatus.Draft, ct);

    protected override Task<bool> LinkedToUserAsync(Guid id, CancellationToken ct) =>
        Db.Users.AnyAsync(u => u.SupplierUuid == id && u.Status == RecordStatus.Active, ct);
}
