#!/usr/bin/env python3
"""
Builds the bundled icon font.

Run after adding a new <mat-icon> to the app:

    pip install fonttools brotli
    npm install --save-dev material-symbols
    python3 tools/build-icon-font.py

It scans the source for icon names, writes a subset of Material Symbols Outlined to
public/fonts/material-symbols-subset.woff2 and regenerates src/app/shared/icon-codepoints.ts.
"""
import pathlib
import re
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'node_modules/material-symbols/material-symbols-outlined.woff2'
FONT_OUT = ROOT / 'public/fonts/material-symbols-subset.woff2'
MAP_OUT = ROOT / 'src/app/shared/icon-codepoints.ts'

PATTERNS = [
    re.compile(r'<mat-icon[^>]*>\s*([a-z_0-9]+)\s*</mat-icon>'),
    re.compile(r"icon:\s*'([a-z_0-9]+)'"),
    re.compile(r"fontIcon=\"([a-z_0-9]+)\""),
]
# An interpolated icon, e.g. <mat-icon>{{ open() ? 'visibility_off' : 'visibility' }}</mat-icon>:
# the expression is not an icon name, so the quoted literals inside it are taken instead.
INTERPOLATED = re.compile(r'<mat-icon[^>]*>\s*\{\{(.*?)\}\}\s*</mat-icon>', re.S)
LITERAL = re.compile(r"'([a-z][a-z_0-9]*)'")


def collect_names() -> list[str]:
    names: set[str] = set()
    for path in (ROOT / 'src').rglob('*'):
        if path.suffix not in {'.ts', '.html'}:
            continue
        text = path.read_text(encoding='utf-8')
        for pattern in PATTERNS:
            names.update(pattern.findall(text))
        for expression in INTERPOLATED.findall(text):
            names.update(LITERAL.findall(expression))
    return sorted(names)


def main() -> int:
    if not SOURCE.exists():
        print(f'Missing {SOURCE}. Run: npm install --save-dev material-symbols', file=sys.stderr)
        return 1

    names = collect_names()
    cmap = TTFont(SOURCE).getBestCmap()
    reverse: dict[str, int] = {}
    for code_point, glyph in cmap.items():
        reverse.setdefault(glyph, code_point)

    unknown = [n for n in names if n not in reverse]
    if unknown:
        print('These icon names are not in Material Symbols:', ', '.join(unknown), file=sys.stderr)
        return 1

    pairs = [(n, reverse[n]) for n in names]
    MAP_OUT.write_text(
        '/**\n * Icon name -> code point in the bundled Material Symbols subset.\n'
        ' * Generated by tools/build-icon-font.py - run it again after adding new icons.\n */\n'
        'export const ICON_CODEPOINTS: Readonly<Record<string, string>> = {\n'
        + ''.join(f"  {name}: '\\u{cp:04x}',\n" for name, cp in pairs)
        + '};\n',
        encoding='utf-8',
    )

    subset.main([
        str(SOURCE),
        f'--output-file={FONT_OUT}',
        '--flavor=woff2',
        '--layout-features=',
        '--unicodes=' + ','.join(f'U+{cp:04X}' for _, cp in pairs),
        '--no-hinting', '--desubroutinize', '--drop-tables+=DSIG',
    ])
    print(f'{len(pairs)} icons -> {FONT_OUT.relative_to(ROOT)} ({FONT_OUT.stat().st_size // 1024} KB)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
